//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Student_Login
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string User_ID { get; set; }
        public string Seat_No { get; set; }
        public string Stream { get; set; }
        public string Paper_ID { get; set; }
        public string Sub_Code { get; set; }
        public string Batch { get; set; }
        public string Password { get; set; }
    }
}
