//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Student
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IP_Address { get; set; }
        public string Index_No { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<int> Division_ID { get; set; }
        public string GR_No { get; set; }
        public string Name { get; set; }
        public string Seat_No { get; set; }
        public Nullable<double> Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
