//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Question2
    {
        public int ID { get; set; }
        public string User_ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string IP_Address { get; set; }
        public string Seat_No { get; set; }
        public string Sub_Code { get; set; }
        public string Index_No { get; set; }
        public string Paper_No { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public string Question_No { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Correct_Answer { get; set; }
        public string Model_Answer { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
