//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question_Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Create_School_College
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string Institute_Name { get; set; }
        public string User_ID { get; set; }
        public string Name { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
